#Config v1.3.0
Messages:
  prefix: "&6[&eDivineCoins&6]: "
  give: "&eYou just gave %Amount% to %Player%"
  receive: "&eYou just received %Amount% from %Player%"
  take: "&eYou just took %Amount% from %Player%"
  set: "&eYou just set %Player%'s coins balance to %Amount%"
  check-others: "&e%Player%'s coins are %Amount%"
  check-self: "&eYour coins are %Amount%"
  pay: "&eYou just sent %Amount% to %Player%"
  reload: "&cSuccessfully reloaded the config!"

Economy:
  starting-amount: 0
  min-payment: 1
  max-payment: 10000000
  

Blocks-Feature:
  enabled: true
  blacklisted-worlds:
    - "world_the_end"
  #Use %Coins% to get the coins given to the player & %Type% to get the block name.
  message: "&aYou just received &6%Coins% coins&a for breaking a(n) &e%Type% block"
  #If players break and replace the block to duplicate coins, they will not receive any coins from the already broken blocks.
  Blocks:
    block1:
      type: "IRON_ORE"
      coins: 4
    block2:
      type: "EMERALD_ORE"
      coins: 12
    block3:
      type: "GOLD_ORE"
      coins: 8
#   block4:
#     type: "SPONGE"
#     coins: 5



GUI:
  enabled: true
  Main-Menu:
    #Size can be between 1-6
    size: 3
    title: "&eCoins Main Menu"
    #Fills the gui's borders with the specified item. leave empty "" to disable.
    fill-border-with-item: "RED_STAINED_GLASS_PANE"
    fill-item-name: "&7"
    fill-item-lore:
      - "&7&m-----------------------"
    #All items listed on the gui.
    Items:
      item1:
        material: "EMERALD"
        name: "&6Shop menu."
        lore:
          - ""
          - "&f&nClick to open the coins shop menu&f."
        place-X: 4
        place-Y: 1
        action: "OPEN_SHOP_GUI"
  Shop-Menu:
    enabled: true
    size: 5
    title: "&eCoins Shop"
    #Fills the gui's borders with the specified item. leave empty "" to disable.
    fill-border-with-item: "ORANGE_STAINED_GLASS_PANE"
    fill-item-name: "&7"
    fill-item-lore:
      - "&7&m-----------------------"
    Items:
      item1:
        #This will be displayed in the gui
        material: "ENDER_PEARL"
        #This will be displayed in the gui
        name: "&a&lClick to purchase an enderpearl"
        #This will be displayed in the gui
        lore:
          - ""
          - "&fLeft-Click to buy for:&a &n%Price%&f Coins."
          - "&fRight-Click to sell for:&c &n%Sell-Price%&f Coins."
          - ""
          - "&f&nCoins:&6 %Coins%"
        place-X: 1
        place-Y: 1
        #price for buying the specific item with coins.
        price: 10
        #Sell price of the item. Leave to 0 to disable.
        sell-price: 8
        #Amount to display in the gui.
        #Amount that will be sold from the item.
        amount: 1
        #Commands to execute when the player purchases the specified item.
        #Use %Player% to get the player name.
        commands:
          - "give %Player% enderpearl 1"
        #The message the player will receive after purchasing the specified item.
        #Use %Price% to get the item's price
        message: "&aYou just purchased an enderpearl with &6%Price% coins."
        message-sell: "&aYou just sold an enderpearl for &c%Sell-Price%&a coins."
        #The message the player will receive if he does not have enough coins.
        not-enough-coins: "&cYou do not have enough coins to purchase this item!"
        #The message the player will receive if he does not have enough items to sell.
        not-enough-items: "&cYou do no have enough items to sell."




